name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-nginx-image:latest .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker tag my-nginx-image:latest ${{ secrets.DOCKER_USERNAME }}/my-nginx-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-image:latest

    # SSH into EC2 and deploy
    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          # Stop any running container
          docker stop my-nginx-container || true
          docker rm my-nginx-container || true

          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-nginx-image:latest

          # Run the Docker container
          docker run -d --name my-nginx-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-nginx-image:latest
        EOF